ALPHABET_LENGTH = 4

NUCLEOTIDE_A = 'A'
NUCLEOTIDE_C = 'C'
NUCLEOTIDE_G = 'G'
NUCLEOTIDE_T = 'T'
NUCLEOTIDE_U = 'U'

NUCLEOTIDE_CHARACTERS = [
    NUCLEOTIDE_A,
    NUCLEOTIDE_C,
    NUCLEOTIDE_G,
    NUCLEOTIDE_T,
    NUCLEOTIDE_U,
    ]

NUCLEOTIDE_COMPLEMENTS = {
    NUCLEOTIDE_A: NUCLEOTIDE_T,
    NUCLEOTIDE_C: NUCLEOTIDE_G,
    NUCLEOTIDE_G: NUCLEOTIDE_C,
    NUCLEOTIDE_T: NUCLEOTIDE_A,
    NUCLEOTIDE_U: NUCLEOTIDE_A,
    }

SPECIAL_CHARACTER_W = 'W'
SPECIAL_CHARACTER_S = 'S'
SPECIAL_CHARACTER_M = 'M'
SPECIAL_CHARACTER_K = 'K'
SPECIAL_CHARACTER_R = 'R'
SPECIAL_CHARACTER_Y = 'Y'
SPECIAL_CHARACTER_B = 'B'
SPECIAL_CHARACTER_D = 'D'
SPECIAL_CHARACTER_H = 'H'
SPECIAL_CHARACTER_V = 'V'
SPECIAL_CHARACTER_N = 'N'

SPECIAL_CHARACTERS = {
    SPECIAL_CHARACTER_W: (NUCLEOTIDE_A, NUCLEOTIDE_T),
    SPECIAL_CHARACTER_S: (NUCLEOTIDE_C, NUCLEOTIDE_G),
    SPECIAL_CHARACTER_M: (NUCLEOTIDE_A, NUCLEOTIDE_C),
    SPECIAL_CHARACTER_K: (NUCLEOTIDE_G, NUCLEOTIDE_T),
    SPECIAL_CHARACTER_R: (NUCLEOTIDE_A, NUCLEOTIDE_G),
    SPECIAL_CHARACTER_Y: (NUCLEOTIDE_C, NUCLEOTIDE_T),
    SPECIAL_CHARACTER_B: (NUCLEOTIDE_C, NUCLEOTIDE_G, NUCLEOTIDE_T),
    SPECIAL_CHARACTER_D: (NUCLEOTIDE_A, NUCLEOTIDE_G, NUCLEOTIDE_T),
    SPECIAL_CHARACTER_H: (NUCLEOTIDE_A, NUCLEOTIDE_C, NUCLEOTIDE_T),
    SPECIAL_CHARACTER_V: (NUCLEOTIDE_A, NUCLEOTIDE_C, NUCLEOTIDE_G),
    SPECIAL_CHARACTER_N: (NUCLEOTIDE_A, NUCLEOTIDE_C, NUCLEOTIDE_G, NUCLEOTIDE_T),
    }
